server:
  port: 8080

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  security:
    user:
      name: test
      password: test

management:
  endpoint:
    health:
      show-details: when_authorized
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /monitor
  server:
    port: 8088



info:
  app:
    name: spring-boot-actuator
    version: 1.0.0
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@
